#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""GGGOM Geodistributed Getter Of Movies Client Executable."""

from client import Client
from optparse import OptionParser
import signal

def parse_args():
    usage = ("%prog [options] server_ip[:port]...\n\n"
             "This is the client program.\n"
             "If no port is given for the server, 40 is used.")

    parser = OptionParser(usage)

    options, args = parser.parse_args()

    if len(args) != 1:
        parser.error('Provide exactly one server address.')

    def parse_address(arg):
        if ':' not in arg:
            host = arg
            port = '40'
        else:
            host, port = arg.split(':', 1)

        if not port.isdigit():
            parser.error('Ports must be integers.')

        return host, int(port)

    host, port = parse_address(args[0])

    return host, port, options

if __name__ == '__main__':
    # signal.signal(signal.SIGINT, signal.SIG_IGN)

    host, port, options = parse_args()

    Client(host, port, options).run()
