#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""GGGOM Geodistributed Getter Of Movies Download Server Executable."""

from download_server import DownloadServer
from optparse import OptionParser
import signal

def parse_args():
    usage = ("%prog [options] server_ip[:port]...\n\n"
             "This is the download server program.\n"
             "If no port is given for the central server, 26 is used.\n"
             "If no port is given for clients, 16 is used.")

    parser = OptionParser(usage)

    help = "The port to listen on. Default is 16."
    parser.add_option('-c', '--client-port', type='int', help=help,
                      dest="client_port")

    options, args = parser.parse_args()

    if len(args) != 1:
        parser.error('Provide exactly one server address.')

    def parse_address(arg):
        if ':' not in arg:
            host = arg
            port = '26'
        else:
            host, port = arg.split(':', 1)

        if not port.isdigit():
            parser.error('Ports must be integers.')

        return host, int(port)

    host, port = parse_address(args[0])

    if options.client_port is None:
        client_port = 16
    else:
        client_port = parse_port(options.client_port)

    return host, port, client_port, options

if __name__ == '__main__':
    # signal.signal(signal.SIGINT, signal.SIG_IGN)

    host, port, client_port, options = parse_args()

    DownloadServer(host, port, client_port, options).run()
